spring:
  datasource:
    url: jdbc:mysql://localhost:3306/listingApp?useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
    username: root
    password: rootroot
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
